name: Catalystic
favicon: null
layout_spectrum: 0.2827
typography_spectrum: 0.055326120695099235
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#404041'
    - '#da1e46'
    - '#000000'
    - '#830f27'
    - '#c8c8c8'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
